#!/usr/bin/env python3
"""
Builds the Domain Contacts pack for the Local Contact Avatars add-on.

Input:   domains_map.csv, columns domain,source_image,category
         logos in images-source/
Output:  images-reworked/<domain>.png   128x128 PNG per row
         review.md                      one block per row, open in VS Code (Ctrl+Shift+V)
         <RELEASE_DIR>/domain-contacts-it.vcf and SHA256SUMS

Every row is processed on every run; the output only changes when the CSV or a logo changes. A row whose logo is missing is reported,
left out of the vcf, and the script exits with status 1 at the end.

Run from anywhere:  python3 create-vcf/create_vcf.py
Requires Pillow.
"""

import base64
import csv
import hashlib
import pathlib
import sys
import uuid

from PIL import Image

HERE = pathlib.Path(__file__).resolve().parent
CSV_FILE = HERE / "domains_map.csv"
SOURCE_DIR = HERE / "images-source"
IMAGES_DIR = HERE / "images-reworked"
REVIEW_FILE = HERE / "review.md"
# The vcf goes into release/ of this repository.
RELEASE_DIR = HERE.parent / "release"
VCF_FILE = RELEASE_DIR / "domain-contacts-it.vcf"
SUMS_FILE = RELEASE_DIR / "SHA256SUMS"

# 128 px canvas, logo scaled to LOGO_BOX, the rest is padding in the color
# sampled at the top-left corner of the source (white if transparent there).
CANVAS = 128
LOGO_BOX = 108
BG = "#ffffff"


def esc(text):
    # vCard text escaping (RFC 6350 3.4)
    return (text.replace("\\", "\\\\").replace(";", "\\;")
                .replace(",", "\\,").replace("\n", "\\n"))


with CSV_FILE.open(encoding="utf-8", newline="") as f:
    rows = list(csv.DictReader(f))
if not rows:
    sys.exit("domains_map.csv has no rows")

IMAGES_DIR.mkdir(exist_ok=True)
RELEASE_DIR.mkdir(parents=True, exist_ok=True)

review = ["# Domain Contacts review", "", "Generated by create_vcf.py, do not edit.", ""]
cards = []
seen = set()
errors = 0

for row in rows:
    domain = row["domain"].strip().lower()
    source = row["source_image"].strip()
    category = row.get("category", "").strip()
    # display name from the file name: poste_italiane.png -> "Poste Italiane"
    fn = pathlib.Path(source).stem.replace("_", " ").replace("-", " ").title()
    out_png = IMAGES_DIR / f"{domain}.png"

    problems = []
    if not domain or "/" in domain or "@" in domain or ":" in domain:
        problems.append("domain must be a bare host name, example amazon.it")
    if domain in seen:
        problems.append("duplicate domain")
    seen.add(domain)
    if not source:
        problems.append("source_image is empty")
    elif not (SOURCE_DIR / source).is_file():
        problems.append(f"source_image not found in images-source/: {source}")

    # --- image ---------------------------------------------------------------
    source_info = ""
    if not problems:
        im = Image.open(SOURCE_DIR / source).convert("RGBA")
        source_info = f"{source} ({im.width}x{im.height})"

        # 1. flatten transparency onto white
        flat = Image.new("RGBA", im.size, BG)
        flat.alpha_composite(im)
        im = flat.convert("RGB")

        # 2. margin color = median of a 3% patch at the top-left corner (a single
        #    pixel can be an edge line or a compression artifact); pad to a
        #    square with it. Nothing is cropped: the source is shown as it is.
        k = max(2, min(im.width, im.height) * 3 // 100)
        patch = list(im.crop((0, 0, k, k)).get_flattened_data())
        margin = tuple(sorted(px[c] for px in patch)[len(patch) // 2] for c in range(3))
        side = max(im.width, im.height)
        square = Image.new("RGB", (side, side), margin)
        square.paste(im, ((side - im.width) // 2, (side - im.height) // 2))

        # 3. scale to LOGO_BOX, center on a canvas of the margin color
        square = square.resize((LOGO_BOX, LOGO_BOX), Image.LANCZOS)
        canvas = Image.new("RGB", (CANVAS, CANVAS), margin)
        canvas.paste(square, ((CANVAS - LOGO_BOX) // 2, (CANVAS - LOGO_BOX) // 2))
        canvas.save(out_png, format="PNG", optimize=True)

    # --- review block ---------------------------------------------------------
    review.append(f"## {domain}")
    review.append("")
    review.append(f"- fn: {fn}")
    review.append(f"- category: {category}")
    review.append(f"- source: {source_info or source or 'missing'}")
    for p in problems:
        review.append(f"- PROBLEM: {p}")
    review.append("")
    if not problems:
        review.append(f'<img src="images-reworked/{out_png.name}" width="128">')
        review.append("")

    if problems:
        errors += 1
        print(f"[{domain or '?'}] " + "; ".join(problems), file=sys.stderr)
        continue

    # --- vcard ----------------------------------------------------------------
    photo_b64 = base64.b64encode(out_png.read_bytes()).decode("ascii")
    # uuid5 of the URL: the UID never changes across rebuilds
    uid = uuid.uuid5(uuid.NAMESPACE_URL, f"https://{domain}/")
    lines = [
        "BEGIN:VCARD",
        "VERSION:4.0",
        "PRODID:-//Local Contact Avatars//Domain Contacts 1.0//EN",
        f"UID:urn:uuid:{uid}",
        "KIND:org",
        f"FN:{esc(fn)}",
        f"ORG:{esc(fn)}",
        "CATEGORIES:domain-contact",
        f"URL:https://{domain}/",
        f"NOTE:Exact domain {domain}",
        f"PHOTO:data:image/png;base64,{photo_b64}",
        "END:VCARD",
    ]
    # RFC 6350 3.2 folding: 75 octets per line, continuation lines start with a space, CRLF
    folded = []
    for line in lines:
        folded.append(line[:75])
        rest = line[75:]
        while rest:
            folded.append(" " + rest[:74])
            rest = rest[74:]
    cards.append("\r\n".join(folded) + "\r\n")

REVIEW_FILE.write_text("\n".join(review), encoding="utf-8")
VCF_FILE.write_text("".join(cards), encoding="utf-8", newline="")

# SHA256SUMS in `sha256sum` format, file names only, for everything in release/
sums = []
for path in sorted(RELEASE_DIR.glob("*.xpi")) + sorted(RELEASE_DIR.glob("*.vcf")):
    sums.append(f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.name}")
SUMS_FILE.write_text("\n".join(sums) + "\n", encoding="utf-8")

print(f"{REVIEW_FILE.name}: {len(rows)} rows")
print(f"{VCF_FILE}: {len(cards)} contacts")
print(f"{SUMS_FILE.name}: {len(sums)} files")
if errors:
    print(f"{errors} row(s) with problems, see stderr and review.md", file=sys.stderr)
    sys.exit(1)
